### ISSUE TITLE
Tema odobrena uz navedena proširenje

### ISSUE THREAD

**Issue by vladaindjic** [ivanmrsulja/hotels-at-last#1]
Dobar dan, kolega @ivanmrsulja ,

Tema deluje interesantno, ali su potrebna neka proširenja:
- Funkcnionalnosti neregistrovanog korisnika:
  - Pretragu omogućiti po još nekim kriterijumima (npr. posedovanje parking mesta, klima uređaja, TV, mašina, itd.). Možete baciti pogled šta sve ima [booking.com](https://www.booking.com/index.sr.html?label=gen173nr-1DCAEoggI46AdIM1gEaMEBiAEBmAEkuAEZyAEM2AED6AEBiAIBqAIDuALA5vGRBsACAdICJDQ0NjVhYjgyLTE3YWMtNGRiMy1iZWUyLTNiMjJkMTdjNWU2MNgCBOACAQ;sid=9bd1bae186a0d24e036a12a93a6bb342;keep_landing=1&sb_price_type=total&) i uzeo deo toga.
 - Funkcionalnosti registrovanog korisnika:
   -  Pored rezervacija, potrebno je omogućiti i poništavanje rezervacija. 
   - Nakon završenog boravka, korisniku dati mogućnost da oceni objekat i da svoj utisak u vidu komentara.
   - Omogućiti prijavu korisnika za nedolične komentare.
   - U zavisnosti od broja rezervacija, korisnike rangirati i davati im određene povlastice u vidu popusta (proširenje za diplomski).
- Menadžer hotela (nova rola u sistemu - proširenje za diplomski)
  - Određuje posebne povlastice u hotelu shodno rangu korisnika (proširenje za diplomski)
- Funkcionalnosti administratora:
  - Blokiranje korisnika na određeni vremenski period zbog nedoličnog ponašanja 

Da li planirate izradu diplomskog? Ukoliko je odgovor da, zamolio bih Vas da kontaktirate profesora i prosledite mu link do ovog issue-a.

Pozdrav,
Vladimir

**Comment by vladaindjic** [comment]
## Drugi način u pristupu za razvoj mikroservisa

Takođe, postoji mogućnost da iskoristite i jedan alata za upotrebu mikroservisa i na taj način izbegne Rust, a možda i Go. U pitanju je jezik za modelovanje mikroservisnih arhitektura Silvera. [Na ovom linku](https://docs.google.com/forms/d/e/1FAIpQLSc6ZplKMRMMD-dJZ8gzE362qcs8LMUG8Ajusr1zP-aAHsjEOg/viewform) možete pronaći anketu koja se tiče korisnosti ovog alata. Vaš zadatak za potrebe polaganja ovog predmeta bi bio da se prijavite za anketu, dobijete neke zadatke koje treba da rešite upotrebom ovog alata, te popunite upitnik o utiscima za korišćenje ovog alata. Nakong toga biste mogli odbraniti projekat tako što biste demonstrirali kako ovaj alat radi. Takođe, moguća će biti proširenja i za diplomski rad.

Više informacija o ovome će postaviti profesor na grupi, a i pričati na sledećem predavanju. Kako Vam se čini ovako nešto?

**Comment by ivanmrsulja** [comment]
Dobar dan @vladaindjic ,
Hvala na ultra-brzom odgovoru 😄, trenutno sam dodao samo proširenja koja ste naveli kao obavezna za najveću ocjenu. Predao sam predlog diplomskog rada iz drugog predmeta i čekam odgovor tako da u momentu neću dodavati proširenja za diplomski rad iz ovog predmeta. Ukoliko se ipak budem odlučio za ovaj predmet, proširenja će biti dodata i kontaktiraću profesora. Što se tiče drugog načina polaganja predmetnog projekta (upotreba Silvera alata), mislim da nisam zainteresovan jer želim da probam razvoj mikroservisa u GO programskom jeziku.
